const array = [{ WORKOUT_ID: 7, WORKOUT_EXERCISE_ID: 10, EXERCISE_NAME: '1/4 Squat Jumps', EXERCISE_DURATION: 2, REST_DURATION: 2 },
  { WORKOUT_ID: 7, WORKOUT_EXERCISE_ID: 11, EXERCISE_NAME: 'Alternating Jump Lunges', EXERCISE_DURATION: 3, REST_DURATION: 4 }];


const { EXERCISE_DURATION, REST_DURATION } = array[1];
console.log({ EXERCISE_DURATION, REST_DURATION });
